[package]
name = "floc"
description = "Count the lines in your codebase."
version = "0.1.0"
authors = ["interrrp <int@addictedto.coffee>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
